### ISSUE TITLE
fix -race flag in alpine-gcc

### ISSUE THREAD

**Issue by kamilsk** [kamilsk/shared#13]
-race flag not work in all alpine-gcc images

**Comment by kamilsk** [comment]
https://github.com/docker-library/golang/issues/86

**Comment by kamilsk** [comment]
https://github.com/golang/go/issues/14481

**Comment by kamilsk** [comment]
try with next configuration:
```
RUN apk add --update -t build-deps curl go git libc-dev gcc libgcc
```

**Comment by mbana** [comment]
do you have a minimal example of this working?
it looks like the `-race` requires `libstd++` as well. i could be wrong.

**Comment by kamilsk** [comment]
@mbana, no, I don't have any working example. I was not able to make it works.

**Comment by aymone** [comment]
@kamilsk This are not working... The issue is about that libs:
https://github.com/google/sanitizers
