### ISSUE TITLE
add uuid research

### ISSUE THREAD

**Issue by kamilsk** [kamilsk/shared#381]
- https://github.com/satori/go.uuid
  - critical defect https://github.com/satori/go.uuid/issues/73
- https://github.com/google/uuid
- https://github.com/hashicorp/go-uuid
  - ~the same problem as satori package~
- https://github.com/kevinburke/go.uuid
  - fork of satori package
- https://github.com/jakehl/goid
  - ~has the same problem~

**Comment by as** [comment]
>the same problem as satori package
No. The hashicorp package uses the `rand.Read`  package function, which states:

```
func Read(b []byte) (n int, err error)
    Read is a helper function that calls Reader.Read using io.ReadFull. On
    return, n == len(b) if and only if err == nil.
```

The satori package uses an `io.Reader` called `rand`

**Comment by kamilsk** [comment]
@as, wow. How did you find this issue? I just opened it 29 minutes ago 👀

And thanks for your clarification. I'm not deep dive into the code of these packages yet.

**Comment by muesli** [comment]
@kamilsk You mentioning the issue (go.uuid#73) creates a cross reference there, linking to this issue.

**Comment by as** [comment]
Also, the `https://github.com/jakehl/goid` is free of that defect as well.
